# Generated by Django 4.1.5 on 2023-04-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='field',
            field=models.CharField(default='Electrical', max_length=50),
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='Your Group', max_length=50),
        ),
    ]
