# Generated by Django 4.1.5 on 2023-04-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_field_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='des',
            field=models.CharField(default='None', max_length=150),
        ),
    ]
