# Generated by Django 4.1.5 on 2023-04-30 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_alumni_profile_image_and_more'),
        ('groups', '0006_alter_group_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='post_alm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_alm', to='user.alumni'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_std',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_std', to='user.student'),
        ),
    ]
