# Generated by Django 4.1.5 on 2023-05-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alumni_banner_image_student_banner_image'),
        ('groups', '0009_group_banner_group_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='answers/images')),
                ('videos', models.FileField(null=True, upload_to='answers/videos')),
                ('alumnis', models.ManyToManyField(to='user.alumni')),
                ('students', models.ManyToManyField(to='user.student')),
            ],
        ),
    ]
