# Generated by Django 4.1.5 on 2023-05-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='videos',
            new_name='video',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shares',
        ),
        migrations.AddField(
            model_name='post',
            name='answers',
            field=models.ManyToManyField(to='groups.answer'),
        ),
        migrations.AddField(
            model_name='post',
            name='downvote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='upvote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
