# Generated by Django 4.1.5 on 2023-05-13 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alumni_banner_image_student_banner_image'),
        ('groups', '0011_rename_videos_answer_video_remove_post_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvotes', models.BooleanField(default=False)),
                ('downvote', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='alumnis',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='students',
        ),
        migrations.AlterField(
            model_name='post',
            name='downvote',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvote',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='answer',
            name='alumnis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ans_alm', to='user.alumni'),
        ),
        migrations.AddField(
            model_name='answer',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ans_std', to='user.student'),
        ),
    ]
