# Generated by Django 4.1.5 on 2023-04-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_alumni_user_alter_student_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='profile_image',
            field=models.ImageField(default='media/profile_pics/defalut.jpg', upload_to='media/profile_pics/alumnis'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(default='media/profile_pics/defalut.jpg', upload_to='media/profile_pics/students'),
        ),
    ]
