# Generated by Django 4.1.5 on 2023-04-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_alumni_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='profile_image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/alumnis'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/students'),
        ),
    ]
