# Generated by Django 4.1.5 on 2023-05-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_alumni_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='banner_image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/alumnis'),
        ),
        migrations.AddField(
            model_name='student',
            name='banner_image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/students'),
        ),
    ]
